---
openstack_instances: 
  vars:
    GUID: "{{ lookup('ENV','GUID') }}"

  - instance_name: app1
    AnsibleGroup: app_servers
    deployment: prod
    security_group_name: "{{GUID}}-HostSG"
    image: "{{ _server_image | default('rhel-8.3') }}"
    openstack_cloud: "{{GUID}}-project"
    flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
    key_name: "{{GUID}}-keypair"
    network: "{{GUID}}-dev-network"
  
  - instance_name: app2
    AnsibleGroup: app_servers
    deployment: prod
    security_group_name: "{{GUID}}-HostSG"
    image: "{{ _server_image | default('rhel-8.3') }}"
    openstack_cloud: "{{GUID}}-project"
    flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
    key_name: "{{GUID}}-keypair"
    network: "{{GUID}}-dev-network"
 
 - instance_name: appdb1
    AnsibleGroup: database_servers
    deployment: prod
    security_group_name: "{{GUID}}-HostSG"
    image: "{{ _server_image | default('rhel-8.3') }}"
    openstack_cloud: "{{GUID}}-project"
    flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
    key_name: "{{GUID}}-keypair"
    network: "{{GUID}}-dev-network"
 
 - instance_name: frontend1
    AnsibleGroup: load_balancers
    deployment: prod
    security_group_name: "{{GUID}}-HostSG"
    image: "{{ _server_image | default('rhel-8.3') }}"
    openstack_cloud: "{{GUID}}-project"
    flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
    key_name: "{{GUID}}-keypair"
    network: "{{GUID}}-dev-network"

...


















#   - instance_name: app1
#     group: apps
#     deployment: dev
#     security_group_name: apps

#   - instance_name: app2
#     group: apps
#     deployment: dev
#     security_group_name: apps

#   - instance_name: db
#     group: appdbs
#     deployment: dev
#     security_group_name: db

#   - instance_name: frontend
#     group: frontends
#     deployment: dev
#     security_group_name: frontend
...
