---

postgres_info:
  postgres_user: postgres
  postgres_users:
    - name: flask
      password: redhat
      database: flask_db
      state: present
      priv: ALL
  postgres_databases:
    - name: flask_db
      owner: flask
    - name: books_store
      owner: flask

postgres_packages:
  - postgresql10 
  - postgresql10-server 
  - postgresql10-contrib 
  - postgresql10-libs

postgres_services: 
  - postgresql-10.service

...
